# Generated by Django 5.0.3 on 2024-03-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='em_equipamento',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='idade_minima_aluno',
            new_name='idade_minima',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
