# Generated by Django 5.0.3 on 2024-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_rename_em_equipamento_exercicio_ativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='ativo',
            new_name='em_equipamento',
        ),
        migrations.RenameField(
            model_name='exercicio',
            old_name='idade_minima',
            new_name='idade_minima_aluno',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
